POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Caneca Rick Sanches",
    "price": 25.12,
    "image_url": "https://m.media-amazon.com/images/I/51mBeKZKW5L._AC_SL1000_.jpg"
}
###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "alice",
    "email": "nopaisdasmaravilhas@gmail.com",
    "password": "coelhobranco"
}
###
GET http://localhost:3003/users

###
GET http://localhost:3003/products

###

POST http://localhost:3003/purchases
Content-type: application/json

{
    "user_id": "1655476393940",
    "product_id": "1655490253883",
    "quantity": 3
}

### 
GET http://localhost:3003/1655476393940/purchases
