
# @name register
POST http://localhost:3306/user/signUp
Content-Type: application/json

{
    "name": "Thor",
    "email": "meioChato@gmail.com",
    "password": "123456",
    "role": ""
}

### 
@token = {{register.response.body.token}}



### 
# @name login

POST http://localhost:3306/user/signIn
Content-Type: application/json

{
    "email": "deusDaTramoia@omelhor.com",
    "password": "123456"
}

###

@token = {{login.response.body.token}}

###

POST http://localhost:3306/user/addFriend/f57cf2d1-2bd4-43aa-a716-bfd50d991d23
Content-Type: application/json
Authorization: {{token}}

###

POST http://localhost:3306/user/removeFriend/18af4f6f-f592-41aa-8e86-7fbd2acfcad6
Content-Type: application/json
Authorization: {{token}}

###

GET http://localhost:3306/user/feed
Content-Type: application/json
Authorization: {{token}}

###

POST http://localhost:3306/post/create
Content-Type: application/json
Authorization: {{token}}

{
    "photo": "https://chicorei.imgix.net/18411/310e4320-ddff-11ec-b195-4f31b370b1c8.jpg?auto=compress,format&q=65&w=425&h=600&fit=crop&crop=top&markpad=0&mark=https%3A%2F%2Fchico-rei.imgix.net%2Fimages%2Fsite%2Fproduct%2Fselo-desgaste.png%3Fauto%3Dformat%26w%3D0.60",
    "description": "Alguèm sabe onde eu consigo encontrar essa blusa?",
    "type": "normal"
}

###

GET http://localhost:3306/post/7639ce90-01ea-47c3-9d5e-90631184c3fa
Content-Type: application/json
Authorization: {{token}}

###